export const DECORATORS_PREFIX = 'asycnapi';
export const DECORATORS = {
  ASYNCAPI_CHANNEL: `${DECORATORS_PREFIX}/channel`,
  ASYNCAPI_PUB: `${DECORATORS_PREFIX}/pub`,
  ASYNCAPI_SUB: `${DECORATORS_PREFIX}/sub`,
};
